### ISSUE TITLE
Maybe not a issue, but the question about "reason" field

### ISSUE THREAD

**Issue by excavador** [mschneider82/problem#11]
Hello!

First at all, thank you so much for this library, it's quite useful to have something ready-to-use, instead of implement-in-house

The second - I have a question about "reason" field in output JSON [link to problem.go#L193](https://github.com/mschneider82/problem/blob/master/problem.go#L193) from "master"

[RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807) specifies this field as an example of the problem at the beginning of the specification.

The field "reason" does not exists as field inside RFC. Somehow, you are adding it inside output JSON.
Could you please clarify "why"?

I feel like I am missing some important library design considerations

**Comment by mschneider82** [comment]
You are right, we set reason as a default for the field name when wrapping errors, to support wrapping errors we need some default field key name. If reason does not fit in your usecase, you have to use Custom and wrap the error manual.

**Comment by mschneider82** [comment]
Good point, but I dont get it why using Wrap(err) if you dont want the error shown in the problem response? For me the only reason for Wrap was that i want the error in the response.

 Changing the code would be a breaking change since some users expect that the error is in the problem message.

**Comment by excavador** [comment]
I want reason in sever logs and I what to use UnWrap 
You need to keep "reason" field inside Golang struct, but do NOT include this field in the output JSON or XML

**Comment by mschneider82** [comment]
@excavador i have merged the PR and tagged v1.9.0

**Comment by excavador** [comment]
Thank you!
