### ISSUE TITLE
Need API to get StatusCode back out of Problem, or implement WriteHeaderTo()

### ISSUE THREAD

**Issue by danielbprice** [mschneider82/problem#5]
I'm trying to implement a robust error handler for Echo using `problem.Problem`.  Mostly this was easy.  However, trying to handle the case of HEAD requests is challenging, because a HEAD must not return a body.  So my natural inclination was to do something like this:

```go
func problemHTTPErrorHandler(err error, c echo.Context) {
         var prb *problem.Problem
           ...
         prb = err.(*problem.Problem)

         var writeErr error
         if c.Request().Method == http.MethodHead {
                 writeErr = c.NoContent(prb.Status())
         } else {
                 writeErr = prb.WriteTo(c.Response())
         }
    ...
}
```

However, there is no way, presently, to access the Status() from the problem.  As a workaround, I can write the problem out to JSON, and then unmarshal it to get the status code, but it's a pain in the neck.  I can see a couple of ways to solve this in the library.  We could add Status() as I show above.  Another option would be to add a new WriteHeaderTo() method.  Maybe something like this?

```go
// WriteHeaderTo writes the HTTP headers corresponding to the problem's content type
// and the problem's http statuscode. This is suitable for responding to HEAD requests.
func (p Problem) WriteHeaderTo(w http.ResponseWriter) (int, error) {
        w.Header().Set("Content-Type", ContentTypeJSON)
        if statuscode, ok := p.data["status"]; ok {
                if statusint, ok := statuscode.(int); ok {
                        w.WriteHeader(statusint)
                }
        }
        return nil
}
```

Thanks!!

Edit: If you let me know your preference, I can prepare a pull request.

**Comment by mschneider82** [comment]
I prefer WriteHeaderTo() please also add it to tests so the coverage is fine

Thanks
