### ISSUE TITLE
Can't seem to fetch v1.7.0

### ISSUE THREAD

**Issue by danielbprice** [mschneider82/problem#7]
Hi, thanks so much for taking my PR.  When I tried to get the latest version, I got:

```
% go get schneider.vip/problem@v1.6.0
go: added schneider.vip/problem v1.6.0
% go get schneider.vip/problem@v1.7.0
go: schneider.vip/problem@v1.7.0: unrecognized import path "schneider.vip/problem": https fetch: Get "https://schneider.vip/problem?go-get=1": x509: “TRAEFIK DEFAULT CERT” certificate is not trusted
```

Any idea what I might be doing wrong?

**Comment by danielbprice** [comment]
Workaround:
```
replace schneider.vip/problem => github.com/mschneider82/problem v1.7.0
```

**Comment by mschneider82** [comment]
@danielbprice please test again, I migrated the domain to kubernetes, i think i have fixed 

`
go get schneider.vip/problem@v1.7.0
go: downloading schneider.vip/problem v1.7.0
go: upgraded schneider.vip/problem v1.6.0 => v1.7.0
`
